### ISSUE TITLE
[FEAT] update screen

### ISSUE THREAD

**Issue by hannahf97** [posco3-2/android-service2#1]
## 💡 Issue
update screen 

## 📝 todo
- [x] 패키지명 com.posco.posco_store 로 리팩토링
- [x] mainActivity 화면 변경
- [x] recyclerview 이미지등 정보 가져오기 수정
- [x] search 가능하도록 filter 생성 
- [x] detail page화면 생성
- [x] detail page화면 내용변경 
- [x] recyclerview change
